language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run author
before_deploy:
  - npm build
deploy:
  provider: script
  script: echo "Add deployment command"
  on:
    branch: main
